### ISSUE TITLE
The Luma brand update broke custom code

### ISSUE THREAD

**Issue by robertmclaws** [luma-team/examples#2]
Since Luma does not support recurring events yet, we had the following custom code on our Webflow site to dynamically update all of the register links to the most current event (that way I don't have to go through the whole site every week and manually update each button).

```
<script type="text/javascript">  
$(function() {
  $('[data-zmurl-action="checkout"]').attr("data-zmurl-event-id", "evt-oHsetgaDaZYv5kF");
  window.zmurl && window.zmurl.initCheckout();
});
</script>

<script id="zmurl-checkout" src="https://embed.zmurl.com/checkout-button.js"></script>
```

Looking at the checkout-button.js code, it's clear you made an effort to pick up the old Register buttons with the old attributes. However, I believe you renamed `window.zmurl` to `window.luma`, and forgot to take the same approach to compatibility. That, in turn, broke our custom code, and for several days people were registering for events that took place in the past.

Also, the readme page for this repo needs to be updated with new code examples.

Thanks!

**Comment by vpontis** [comment]
@robertmclaws thanks for the heads up, sorry about that and thanks for the heads up! 

We'll update this repo ASAP

**Comment by robertmclaws** [comment]
No problem! Glad there was a repo where I could post the issue! You might consider updating the script to make `window.zmurl` an active client instance as well, and console.log if `initCheckout()` was called through `window.zmurl` instead of `window.luma`.

HTH!

**Comment by vpontis** [comment]
Updated this, thanks!
